-- ============================================================================
-- 01 · RLS context helpers
-- GENERATED by scripts/gen-rls-policies.mjs from prisma/schema.prisma — DO NOT
-- edit by hand; regenerate instead. Idempotent. Run once.
-- ============================================================================

-- The "app" schema holds the per-request tenant context, read from session
-- variables that the Prisma client extension sets with SET LOCAL inside each
-- transaction (src/lib/db/tenant-context.ts). current_setting(..., true) =
-- missing_ok, so an unset variable returns NULL rather than erroring.
create schema if not exists app;

create or replace function app.current_user_id() returns text
  language sql stable
  as $$ select nullif(current_setting('app.current_user_id', true), '') $$;

create or replace function app.current_org_id() returns text
  language sql stable
  as $$ select nullif(current_setting('app.current_org_id', true), '') $$;

-- Escape hatch for trusted server paths (cron jobs, migrations, admin tooling,
-- the analysis pipeline) that legitimately operate across tenants. The Prisma
-- extension sets app.bypass_rls = 'on' for those code paths explicitly.
create or replace function app.rls_bypassed() returns boolean
  language sql stable
  as $$ select coalesce(current_setting('app.bypass_rls', true), 'off') = 'on' $$;

-- FAIL-OPEN guard. True when NO tenant context has been set on the connection.
-- Every current Prisma query sets nothing, so while this clause is in the
-- policies the app behaves exactly as it does today. The enforce stage
-- (03_enforce.sql) removes this clause to turn protection on.
create or replace function app.no_tenant_context() returns boolean
  language sql stable
  as $$ select app.current_user_id() is null and app.current_org_id() is null $$;
