-- ============================================================================
-- 02 · ENABLE + FORCE RLS · fail-open policies  [SAFE TO APPLY NOW]
-- GENERATED by scripts/gen-rls-policies.mjs from prisma/schema.prisma — DO NOT
-- edit by hand; regenerate instead. Applying this is a no-op for current queries (no context is set → every row passes).
-- ============================================================================

alter table "Document" enable row level security;
alter table "Document" force row level security;
drop policy if exists tenant_isolation on "Document";
create policy tenant_isolation on "Document"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "LegalHold" enable row level security;
alter table "LegalHold" force row level security;
drop policy if exists tenant_isolation on "LegalHold";
create policy tenant_isolation on "LegalHold"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "DocumentAccess" enable row level security;
alter table "DocumentAccess" force row level security;
drop policy if exists tenant_isolation on "DocumentAccess";
create policy tenant_isolation on "DocumentAccess"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "DecisionContainer" enable row level security;
alter table "DecisionContainer" force row level security;
drop policy if exists tenant_isolation on "DecisionContainer";
create policy tenant_isolation on "DecisionContainer"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "AnalysisReservation" enable row level security;
alter table "AnalysisReservation" force row level security;
drop policy if exists tenant_isolation on "AnalysisReservation";
create policy tenant_isolation on "AnalysisReservation"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "BiasComment" enable row level security;
alter table "BiasComment" force row level security;
drop policy if exists tenant_isolation on "BiasComment";
create policy tenant_isolation on "BiasComment"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "BiasTask" enable row level security;
alter table "BiasTask" force row level security;
drop policy if exists tenant_isolation on "BiasTask";
create policy tenant_isolation on "BiasTask"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "AuditLog" enable row level security;
alter table "AuditLog" force row level security;
drop policy if exists tenant_isolation on "AuditLog";
create policy tenant_isolation on "AuditLog"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "UserSettings" enable row level security;
alter table "UserSettings" force row level security;
drop policy if exists tenant_isolation on "UserSettings";
create policy tenant_isolation on "UserSettings"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "VohraPMFResponse" enable row level security;  -- founder-private (userId-scoped)
alter table "VohraPMFResponse" force row level security;
drop policy if exists tenant_isolation on "VohraPMFResponse";
create policy tenant_isolation on "VohraPMFResponse"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "SsoConfiguration" enable row level security;
alter table "SsoConfiguration" force row level security;
drop policy if exists tenant_isolation on "SsoConfiguration";
create policy tenant_isolation on "SsoConfiguration"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "TeamMember" enable row level security;
alter table "TeamMember" force row level security;
drop policy if exists tenant_isolation on "TeamMember";
create policy tenant_isolation on "TeamMember"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id() OR "userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id() OR "userId" = app.current_user_id()));

alter table "TeamInvite" enable row level security;
alter table "TeamInvite" force row level security;
drop policy if exists tenant_isolation on "TeamInvite";
create policy tenant_isolation on "TeamInvite"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "SlackInstallation" enable row level security;
alter table "SlackInstallation" force row level security;
drop policy if exists tenant_isolation on "SlackInstallation";
create policy tenant_isolation on "SlackInstallation"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "Meeting" enable row level security;
alter table "Meeting" force row level security;
drop policy if exists tenant_isolation on "Meeting";
create policy tenant_isolation on "Meeting"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "HumanDecision" enable row level security;
alter table "HumanDecision" force row level security;
drop policy if exists tenant_isolation on "HumanDecision";
create policy tenant_isolation on "HumanDecision"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "Nudge" enable row level security;
alter table "Nudge" force row level security;
drop policy if exists tenant_isolation on "Nudge";
create policy tenant_isolation on "Nudge"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "TeamCognitiveProfile" enable row level security;
alter table "TeamCognitiveProfile" force row level security;
drop policy if exists tenant_isolation on "TeamCognitiveProfile";
create policy tenant_isolation on "TeamCognitiveProfile"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "FounderOsCheckin" enable row level security;  -- founder-private (userId-scoped)
alter table "FounderOsCheckin" force row level security;
drop policy if exists tenant_isolation on "FounderOsCheckin";
create policy tenant_isolation on "FounderOsCheckin"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "FounderOsContentLog" enable row level security;  -- founder-private (userId-scoped)
alter table "FounderOsContentLog" force row level security;
drop policy if exists tenant_isolation on "FounderOsContentLog";
create policy tenant_isolation on "FounderOsContentLog"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "FounderOsSkill" enable row level security;  -- founder-private (userId-scoped)
alter table "FounderOsSkill" force row level security;
drop policy if exists tenant_isolation on "FounderOsSkill";
create policy tenant_isolation on "FounderOsSkill"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "FounderOsWeeklyReview" enable row level security;  -- founder-private (userId-scoped)
alter table "FounderOsWeeklyReview" force row level security;
drop policy if exists tenant_isolation on "FounderOsWeeklyReview";
create policy tenant_isolation on "FounderOsWeeklyReview"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "FounderOsCommitment" enable row level security;  -- founder-private (userId-scoped)
alter table "FounderOsCommitment" force row level security;
drop policy if exists tenant_isolation on "FounderOsCommitment";
create policy tenant_isolation on "FounderOsCommitment"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "FounderOsPrayerJournal" enable row level security;  -- founder-private (userId-scoped)
alter table "FounderOsPrayerJournal" force row level security;
drop policy if exists tenant_isolation on "FounderOsPrayerJournal";
create policy tenant_isolation on "FounderOsPrayerJournal"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "FounderOsReadingProgress" enable row level security;  -- founder-private (userId-scoped)
alter table "FounderOsReadingProgress" force row level security;
drop policy if exists tenant_isolation on "FounderOsReadingProgress";
create policy tenant_isolation on "FounderOsReadingProgress"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "FounderOsDailyGoal" enable row level security;  -- founder-private (userId-scoped)
alter table "FounderOsDailyGoal" force row level security;
drop policy if exists tenant_isolation on "FounderOsDailyGoal";
create policy tenant_isolation on "FounderOsDailyGoal"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "FounderOsPeriodGoal" enable row level security;  -- founder-private (userId-scoped)
alter table "FounderOsPeriodGoal" force row level security;
drop policy if exists tenant_isolation on "FounderOsPeriodGoal";
create policy tenant_isolation on "FounderOsPeriodGoal"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "FounderOsDailyReflection" enable row level security;  -- founder-private (userId-scoped)
alter table "FounderOsDailyReflection" force row level security;
drop policy if exists tenant_isolation on "FounderOsDailyReflection";
create policy tenant_isolation on "FounderOsDailyReflection"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "FounderOsRealityCheckin" enable row level security;  -- founder-private (userId-scoped)
alter table "FounderOsRealityCheckin" force row level security;
drop policy if exists tenant_isolation on "FounderOsRealityCheckin";
create policy tenant_isolation on "FounderOsRealityCheckin"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "FounderOsRealityReflection" enable row level security;  -- founder-private (userId-scoped)
alter table "FounderOsRealityReflection" force row level security;
drop policy if exists tenant_isolation on "FounderOsRealityReflection";
create policy tenant_isolation on "FounderOsRealityReflection"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "SatErrorLogEntry" enable row level security;  -- founder-private (userId-scoped)
alter table "SatErrorLogEntry" force row level security;
drop policy if exists tenant_isolation on "SatErrorLogEntry";
create policy tenant_isolation on "SatErrorLogEntry"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "SatSettings" enable row level security;  -- founder-private (userId-scoped)
alter table "SatSettings" force row level security;
drop policy if exists tenant_isolation on "SatSettings";
create policy tenant_isolation on "SatSettings"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "SatDailySession" enable row level security;  -- founder-private (userId-scoped)
alter table "SatDailySession" force row level security;
drop policy if exists tenant_isolation on "SatDailySession";
create policy tenant_isolation on "SatDailySession"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "SatTestResult" enable row level security;  -- founder-private (userId-scoped)
alter table "SatTestResult" force row level security;
drop policy if exists tenant_isolation on "SatTestResult";
create policy tenant_isolation on "SatTestResult"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "SatVocabCard" enable row level security;  -- founder-private (userId-scoped)
alter table "SatVocabCard" force row level security;
drop policy if exists tenant_isolation on "SatVocabCard";
create policy tenant_isolation on "SatVocabCard"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "MicroDeliberationOutcome" enable row level security;
alter table "MicroDeliberationOutcome" force row level security;
drop policy if exists tenant_isolation on "MicroDeliberationOutcome";
create policy tenant_isolation on "MicroDeliberationOutcome"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "DecisionOutcome" enable row level security;
alter table "DecisionOutcome" force row level security;
drop policy if exists tenant_isolation on "DecisionOutcome";
create policy tenant_isolation on "DecisionOutcome"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "BoardroomPersona" enable row level security;
alter table "BoardroomPersona" force row level security;
drop policy if exists tenant_isolation on "BoardroomPersona";
create policy tenant_isolation on "BoardroomPersona"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id() OR "userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id() OR "userId" = app.current_user_id()));

alter table "ShareLink" enable row level security;
alter table "ShareLink" force row level security;
drop policy if exists tenant_isolation on "ShareLink";
create policy tenant_isolation on "ShareLink"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "NotificationLog" enable row level security;
alter table "NotificationLog" force row level security;
drop policy if exists tenant_isolation on "NotificationLog";
create policy tenant_isolation on "NotificationLog"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "FailedAnalysis" enable row level security;
alter table "FailedAnalysis" force row level security;
drop policy if exists tenant_isolation on "FailedAnalysis";
create policy tenant_isolation on "FailedAnalysis"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "GraphShareLink" enable row level security;
alter table "GraphShareLink" force row level security;
drop policy if exists tenant_isolation on "GraphShareLink";
create policy tenant_isolation on "GraphShareLink"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "BatchUpload" enable row level security;
alter table "BatchUpload" force row level security;
drop policy if exists tenant_isolation on "BatchUpload";
create policy tenant_isolation on "BatchUpload"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "CalibrationProfile" enable row level security;
alter table "CalibrationProfile" force row level security;
drop policy if exists tenant_isolation on "CalibrationProfile";
create policy tenant_isolation on "CalibrationProfile"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id() OR "userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id() OR "userId" = app.current_user_id()));

alter table "CausalEdge" enable row level security;
alter table "CausalEdge" force row level security;
drop policy if exists tenant_isolation on "CausalEdge";
create policy tenant_isolation on "CausalEdge"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "OrgCausalModel" enable row level security;
alter table "OrgCausalModel" force row level security;
drop policy if exists tenant_isolation on "OrgCausalModel";
create policy tenant_isolation on "OrgCausalModel"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "DecisionPrior" enable row level security;
alter table "DecisionPrior" force row level security;
drop policy if exists tenant_isolation on "DecisionPrior";
create policy tenant_isolation on "DecisionPrior"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "DecisionFrame" enable row level security;
alter table "DecisionFrame" force row level security;
drop policy if exists tenant_isolation on "DecisionFrame";
create policy tenant_isolation on "DecisionFrame"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "RedTeamChallenge" enable row level security;
alter table "RedTeamChallenge" force row level security;
drop policy if exists tenant_isolation on "RedTeamChallenge";
create policy tenant_isolation on "RedTeamChallenge"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "DecisionRoom" enable row level security;
alter table "DecisionRoom" force row level security;
drop policy if exists tenant_isolation on "DecisionRoom";
create policy tenant_isolation on "DecisionRoom"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "DecisionRoomInvite" enable row level security;
alter table "DecisionRoomInvite" force row level security;
drop policy if exists tenant_isolation on "DecisionRoomInvite";
create policy tenant_isolation on "DecisionRoomInvite"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "RoomParticipant" enable row level security;
alter table "RoomParticipant" force row level security;
drop policy if exists tenant_isolation on "RoomParticipant";
create policy tenant_isolation on "RoomParticipant"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "BlindPrior" enable row level security;
alter table "BlindPrior" force row level security;
drop policy if exists tenant_isolation on "BlindPrior";
create policy tenant_isolation on "BlindPrior"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "JournalEntry" enable row level security;
alter table "JournalEntry" force row level security;
drop policy if exists tenant_isolation on "JournalEntry";
create policy tenant_isolation on "JournalEntry"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "ApiKey" enable row level security;
alter table "ApiKey" force row level security;
drop policy if exists tenant_isolation on "ApiKey";
create policy tenant_isolation on "ApiKey"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "ToxicCombination" enable row level security;
alter table "ToxicCombination" force row level security;
drop policy if exists tenant_isolation on "ToxicCombination";
create policy tenant_isolation on "ToxicCombination"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "ToxicPattern" enable row level security;
alter table "ToxicPattern" force row level security;
drop policy if exists tenant_isolation on "ToxicPattern";
create policy tenant_isolation on "ToxicPattern"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "DecisionEdge" enable row level security;
alter table "DecisionEdge" force row level security;
drop policy if exists tenant_isolation on "DecisionEdge";
create policy tenant_isolation on "DecisionEdge"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "DecisionBriefRecord" enable row level security;
alter table "DecisionBriefRecord" force row level security;
drop policy if exists tenant_isolation on "DecisionBriefRecord";
create policy tenant_isolation on "DecisionBriefRecord"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "ContextualBiasPattern" enable row level security;
alter table "ContextualBiasPattern" force row level security;
drop policy if exists tenant_isolation on "ContextualBiasPattern";
create policy tenant_isolation on "ContextualBiasPattern"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "FingerprintWarning" enable row level security;
alter table "FingerprintWarning" force row level security;
drop policy if exists tenant_isolation on "FingerprintWarning";
create policy tenant_isolation on "FingerprintWarning"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "ChatSession" enable row level security;
alter table "ChatSession" force row level security;
drop policy if exists tenant_isolation on "ChatSession";
create policy tenant_isolation on "ChatSession"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "ApiUsage" enable row level security;
alter table "ApiUsage" force row level security;
drop policy if exists tenant_isolation on "ApiUsage";
create policy tenant_isolation on "ApiUsage"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "CopilotSession" enable row level security;
alter table "CopilotSession" force row level security;
drop policy if exists tenant_isolation on "CopilotSession";
create policy tenant_isolation on "CopilotSession"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "CopilotOutcome" enable row level security;
alter table "CopilotOutcome" force row level security;
drop policy if exists tenant_isolation on "CopilotOutcome";
create policy tenant_isolation on "CopilotOutcome"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "AnalyticsEvent" enable row level security;
alter table "AnalyticsEvent" force row level security;
drop policy if exists tenant_isolation on "AnalyticsEvent";
create policy tenant_isolation on "AnalyticsEvent"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "VoiceSessionEvent" enable row level security;
alter table "VoiceSessionEvent" force row level security;
drop policy if exists tenant_isolation on "VoiceSessionEvent";
create policy tenant_isolation on "VoiceSessionEvent"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "Subscription" enable row level security;
alter table "Subscription" force row level security;
drop policy if exists tenant_isolation on "Subscription";
create policy tenant_isolation on "Subscription"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "WebhookSubscription" enable row level security;
alter table "WebhookSubscription" force row level security;
drop policy if exists tenant_isolation on "WebhookSubscription";
create policy tenant_isolation on "WebhookSubscription"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id() OR "userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id() OR "userId" = app.current_user_id()));

alter table "DecisionAttribution" enable row level security;
alter table "DecisionAttribution" force row level security;
drop policy if exists tenant_isolation on "DecisionAttribution";
create policy tenant_isolation on "DecisionAttribution"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id()));

alter table "DecisionPlaybook" enable row level security;
alter table "DecisionPlaybook" force row level security;
drop policy if exists tenant_isolation on "DecisionPlaybook";
create policy tenant_isolation on "DecisionPlaybook"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id() OR "userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("orgId" = app.current_org_id() OR "userId" = app.current_user_id()));

alter table "PlaybookInvocation" enable row level security;
alter table "PlaybookInvocation" force row level security;
drop policy if exists tenant_isolation on "PlaybookInvocation";
create policy tenant_isolation on "PlaybookInvocation"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "CalibrationMilestone" enable row level security;
alter table "CalibrationMilestone" force row level security;
drop policy if exists tenant_isolation on "CalibrationMilestone";
create policy tenant_isolation on "CalibrationMilestone"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "DecisionContainerAuditPurchase" enable row level security;
alter table "DecisionContainerAuditPurchase" force row level security;
drop policy if exists tenant_isolation on "DecisionContainerAuditPurchase";
create policy tenant_isolation on "DecisionContainerAuditPurchase"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "ConstellationPriorityCapture" enable row level security;
alter table "ConstellationPriorityCapture" force row level security;
drop policy if exists tenant_isolation on "ConstellationPriorityCapture";
create policy tenant_isolation on "ConstellationPriorityCapture"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "RejectedDecision" enable row level security;
alter table "RejectedDecision" force row level security;
drop policy if exists tenant_isolation on "RejectedDecision";
create policy tenant_isolation on "RejectedDecision"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "GoogleDriveInstallation" enable row level security;
alter table "GoogleDriveInstallation" force row level security;
drop policy if exists tenant_isolation on "GoogleDriveInstallation";
create policy tenant_isolation on "GoogleDriveInstallation"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "OutreachArtifact" enable row level security;  -- founder-private (userId-scoped)
alter table "OutreachArtifact" force row level security;
drop policy if exists tenant_isolation on "OutreachArtifact";
create policy tenant_isolation on "OutreachArtifact"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "WedgeProspect" enable row level security;  -- founder-private (userId-scoped)
alter table "WedgeProspect" force row level security;
drop policy if exists tenant_isolation on "WedgeProspect";
create policy tenant_isolation on "WedgeProspect"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id()));

alter table "DecisionProvenanceRecord" enable row level security;
alter table "DecisionProvenanceRecord" force row level security;
drop policy if exists tenant_isolation on "DecisionProvenanceRecord";
create policy tenant_isolation on "DecisionProvenanceRecord"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "DqiWeightOverride" enable row level security;
alter table "DqiWeightOverride" force row level security;
drop policy if exists tenant_isolation on "DqiWeightOverride";
create policy tenant_isolation on "DqiWeightOverride"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

alter table "AmbientThesisSignal" enable row level security;
alter table "AmbientThesisSignal" force row level security;
drop policy if exists tenant_isolation on "AmbientThesisSignal";
create policy tenant_isolation on "AmbientThesisSignal"
  using (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()))
  with check (app.rls_bypassed() OR app.no_tenant_context() OR ("userId" = app.current_user_id() OR "orgId" = app.current_org_id()));

