import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service | Decision Intel',
  description:
    'Terms and conditions for using the Decision Intel platform. AI-powered decision intelligence for corporate strategy and M&A teams.',
  openGraph: {
    title: 'Terms of Service | Decision Intel',
    description:
      'Terms and conditions for using the Decision Intel platform. AI-powered decision intelligence for corporate strategy and M&A teams.',
  },
};

export default function TermsOfServicePage() {
  return (
    <main
      className="min-h-screen py-24 px-6"
      style={{ background: 'var(--bg-primary)', color: 'var(--text-primary)' }}
    >
      <div className="max-w-3xl mx-auto">
        <Link
          href="/"
          className="inline-flex items-center gap-1 text-sm mb-8 hover:text-white transition-colors"
          style={{ color: 'var(--text-muted)' }}
        >
          &larr; Back to Home
        </Link>

        <h1
          style={{
            fontSize: 'clamp(1.8rem, 3vw, 2.4rem)',
            fontWeight: 700,
            letterSpacing: '-0.02em',
            marginBottom: '8px',
          }}
        >
          Terms of Service
        </h1>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem', marginBottom: '48px' }}>
          Last updated: March 29, 2026
        </p>

        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            gap: '40px',
            fontSize: '0.9rem',
            lineHeight: 1.8,
            color: 'var(--text-muted)',
          }}
        >
          <section>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '12px' }}>
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using Decision Intel (&quot;the Platform&quot;), you agree to be bound
              by these Terms of Service. If you are using the Platform on behalf of an organization,
              you represent that you have the authority to bind that organization to these terms. If
              you do not agree, do not use the Platform.
            </p>
          </section>

          <section>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '12px' }}>
              2. Description of Service
            </h2>
            <p>
              Decision Intel is an AI-powered decision intelligence platform that analyzes
              strategic documents for cognitive bias and decision noise. The Platform provides bias
              detection, noise scoring, decision quality indexing, outcome tracking, and related
              analytics tools. Analysis results are generated by artificial intelligence and should
              be used as a supplement to, not a replacement for, professional judgment.
            </p>
          </section>

          <section>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '12px' }}>
              3. Account Registration
            </h2>
            <p style={{ marginBottom: '12px' }}>
              To use the Platform, you must create an account using Google OAuth. You are
              responsible for:
            </p>
            <ul
              style={{ paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '8px' }}
            >
              <li>Maintaining the security of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>
                Ensuring that your use of the Platform complies with all applicable laws and
                regulations
              </li>
              <li>Notifying us immediately of any unauthorized use of your account</li>
            </ul>
          </section>

          <section>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '12px' }}>
              4. Subscription Plans &amp; Billing
            </h2>
            <p style={{ marginBottom: '12px' }}>
              The Platform offers free and paid subscription tiers. For paid plans:
            </p>
            <ul
              style={{ paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '8px' }}
            >
              <li>Billing occurs monthly or annually depending on your selected plan</li>
              <li>
                You may cancel your subscription at any time; access continues until the end of the
                current billing period
              </li>
              <li>Refunds are handled on a case-by-case basis within 14 days of purchase</li>
              <li>We reserve the right to change pricing with 30 days&apos; notice</li>
              <li>Payment processing is handled securely through Stripe</li>
            </ul>
          </section>

          <section>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '12px' }}>
              5. Acceptable Use
            </h2>
            <p style={{ marginBottom: '12px' }}>You agree not to:</p>
            <ul
              style={{ paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '8px' }}
            >
              <li>
                Upload documents containing illegal content or that you do not have the right to
                analyze
              </li>
              <li>
                Attempt to reverse-engineer, decompile, or extract our proprietary algorithms, bias
                detection models, or scoring methodologies
              </li>
              <li>
                Use the Platform to make automated strategic decisions without human oversight
              </li>
              <li>
                Share your account credentials or allow unauthorized users to access the Platform
              </li>
              <li>Circumvent rate limits, usage quotas, or other technical restrictions</li>
              <li>Use the Platform in any way that could harm, disable, or impair our services</li>
            </ul>
          </section>

          <section>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '12px' }}>
              6. Intellectual Property
            </h2>
            <p style={{ marginBottom: '12px' }}>
              <strong style={{ color: 'var(--text-primary)' }}>Your Content:</strong> You retain
              ownership of all documents and data you upload to the Platform. By uploading, you
              grant us a limited license to process your content solely for the purpose of providing
              analysis services to you.
            </p>
            <p>
              <strong style={{ color: 'var(--text-primary)' }}>Our Platform:</strong> The Decision
              Intel platform, including its AI pipeline, Decision Quality Index methodology, bias
              interaction matrix, noise scoring algorithms, causal models, and all related
              intellectual property, is owned by Decision Intel. You may not copy, modify, or create
              derivative works based on our proprietary technology.
            </p>
          </section>

          <section>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '12px' }}>
              7. AI-Generated Content Disclaimer
            </h2>
            <p>
              Analysis results, bias detections, noise scores, and recommendations generated by the
              Platform are produced by artificial intelligence models. While we strive for accuracy,
              AI-generated content may contain errors, omissions, or inaccuracies.{' '}
              <strong style={{ color: 'var(--text-primary)' }}>
                Decision Intel does not provide investment or strategic advice.
              </strong>{' '}
              Our analysis is intended to augment human decision-making, not replace it. You are
              solely responsible for any decisions made based on Platform outputs.
            </p>
          </section>

          <section>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '12px' }}>
              8. Confidentiality
            </h2>
            <p>
              We understand that documents uploaded to the Platform may contain confidential and
              commercially sensitive information. We commit to treating all uploaded documents as
              confidential, processing them only for providing our services, and not sharing them
              with third parties except as required by our data processing pipeline (see Privacy
              Policy). Documents are encrypted at rest and PII is automatically redacted before AI
              processing.
            </p>
          </section>

          <section>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '12px' }}>
              9. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, Decision Intel shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages, including but not
              limited to loss of profits, data, or investment returns, arising from your use of the
              Platform. Our total liability for any claim shall not exceed the amount you paid us in
              the twelve (12) months preceding the claim.
            </p>
          </section>

          <section>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '12px' }}>
              10. Termination
            </h2>
            <p>
              We may suspend or terminate your account if you violate these Terms. You may delete
              your account at any time through the Platform settings. Upon termination, your data
              will be handled in accordance with our Privacy Policy, including permanent deletion
              within 30 days.
            </p>
          </section>

          <section>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '12px' }}>
              11. Changes to Terms
            </h2>
            <p>
              We may update these Terms from time to time. Material changes will be communicated via
              email or in-app notification at least 30 days before taking effect. Continued use of
              the Platform after changes are effective constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '12px' }}>
              12. Governing Law
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the
              State of Delaware, United States, without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '12px' }}>
              13. Contact
            </h2>
            <p>
              For questions about these Terms, contact us at:{' '}
              <a
                href="mailto:folahanwilliams@gmail.com"
                style={{ color: '#FFFFFF', textDecoration: 'underline' }}
              >
                folahanwilliams@gmail.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
