-- AlterTable
ALTER TABLE "Analysis" ADD COLUMN IF NOT EXISTS "structuredContent" TEXT;
ALTER TABLE "Analysis" ADD COLUMN IF NOT EXISTS "speakers" TEXT[];
ALTER TABLE "Analysis" ADD COLUMN IF NOT EXISTS "noiseStats" JSONB;
ALTER TABLE "Analysis" ADD COLUMN IF NOT EXISTS "noiseBenchmarks" JSONB;
ALTER TABLE "Analysis" ADD COLUMN IF NOT EXISTS "factCheck" JSONB;
ALTER TABLE "Analysis" ADD COLUMN IF NOT EXISTS "compliance" JSONB;
ALTER TABLE "Analysis" ADD COLUMN IF NOT EXISTS "preMortem" JSONB;
ALTER TABLE "Analysis" ADD COLUMN IF NOT EXISTS "sentiment" JSONB;
ALTER TABLE "Analysis" ADD COLUMN IF NOT EXISTS "logicalAnalysis" JSONB;
ALTER TABLE "Analysis" ADD COLUMN IF NOT EXISTS "swotAnalysis" JSONB;
ALTER TABLE "Analysis" ADD COLUMN IF NOT EXISTS "cognitiveAnalysis" JSONB;
ALTER TABLE "Analysis" ADD COLUMN IF NOT EXISTS "simulation" JSONB;
ALTER TABLE "Analysis" ADD COLUMN IF NOT EXISTS "institutionalMemory" JSONB;
