/**
 * Zod validation schema for Decision Brief output.
 *
 * Validates and sanitises the multi-document synthesis generated by
 * Gemini before persisting to the DecisionBriefRecord table.
 */

import { z } from 'zod';

export const KeyFindingSchema = z.object({
  finding: z.string().default(''),
  severity: z.enum(['critical', 'high', 'medium', 'low']).default('medium'),
  sources: z.array(z.string()).default([]),
});

export const BiasEntrySchema = z.object({
  type: z.string().default('Unknown'),
  frequency: z.number().min(0).default(0),
  avgSeverity: z.string().default('medium'),
});

export const RiskEntrySchema = z.object({
  risk: z.string().default(''),
  likelihood: z.string().default('medium'),
  impact: z.string().default('medium'),
});

export const DocumentScorecardEntrySchema = z.object({
  filename: z.string().default('Unknown'),
  score: z.number().min(0).max(100).default(0),
  topBiases: z.array(z.string()).default([]),
  keyInsight: z.string().default(''),
});

export const DecisionBriefSchema = z
  .object({
    executiveSummary: z.string().default('No executive summary available.'),
    keyFindings: z.array(KeyFindingSchema).default([]),
    biasLandscape: z
      .object({
        topBiases: z.array(BiasEntrySchema).default([]),
        crossDocPatterns: z.array(z.string()).default([]),
      })
      .default({ topBiases: [], crossDocPatterns: [] }),
    riskAssessment: z
      .object({
        overallRisk: z.enum(['low', 'medium', 'high', 'critical']).default('medium'),
        topRisks: z.array(RiskEntrySchema).default([]),
      })
      .default({ overallRisk: 'medium', topRisks: [] }),
    recommendation: z
      .object({
        action: z
          .enum(['proceed', 'proceed_with_caution', 'delay', 'reject'])
          .default('proceed_with_caution'),
        rationale: z.string().default(''),
        conditions: z.array(z.string()).default([]),
      })
      .default({ action: 'proceed_with_caution', rationale: '', conditions: [] }),
    documentScorecard: z.array(DocumentScorecardEntrySchema).default([]),
  })
  .passthrough();

export type DecisionBrief = z.infer<typeof DecisionBriefSchema>;
