/**
 * Constellation Next Move — shared type definitions.
 *
 * Locked 2026-05-10. The shapes here are the contract between the
 * rule-based engine, the cross-decision pattern detector, the LLM
 * augmentation layer, the API endpoints, and the UI components.
 *
 * Discipline: every recommendation MUST trace to (a) a category id
 * from NEXT_MOVE_CATEGORIES, (b) a containerId (or container-set for
 * cross-decision patterns), (c) a "why this fires" trace string, and
 * (d) a numeric score for ranking. The trace + the category id are
 * the audit trail — when the user asks "where did this come from?"
 * the answer is the trace.
 */

import type { NextMoveCategoryId } from './next-move-categories';
import type { ValidityClass } from '@/lib/learning/validity-classifier';

/**
 * A single ranked recommendation produced by the engine. The strip
 * shows the top-1 by `finalScore`; the drawer shows the top-N grouped
 * by category.
 */
export interface NextMoveRecommendation {
  /// Stable id for the recommendation (deterministic from inputs +
  /// computed-at timestamp). Used as React key + audit trail.
  id: string;
  /// Category — one of the six in NEXT_MOVE_CATEGORIES.
  categoryId: NextMoveCategoryId;
  /// Primary container the recommendation targets. For cross-decision
  /// patterns, this is the container the user clicks INTO from the
  /// strip; the related set is in `relatedContainerIds`.
  containerId: string;
  containerName: string;
  containerKind: 'investment' | 'acquisition' | 'strategic';
  /// Validity class of the container — drives recommendation
  /// aggressiveness per paper Ch 3 (low-validity environments need
  /// friction-additive framing; high-validity environments need
  /// minimal-friction action).
  validityClass: ValidityClass;
  /// Other containers linked to this recommendation. Populated for
  /// cross_decision_pattern + lineage_drift categories. Empty for
  /// single-container categories.
  relatedContainerIds: string[];
  /// Persona-tuned wording (rendered from PERSONA_FRAMING +
  /// substituteFraming). Three lengths.
  tightLabel: string;
  regularLabel: string;
  detailedLabel: string;
  /// CTA verb (e.g. "Resolve", "Stress-test", "Log outcome"). From
  /// the persona framing template.
  ctaVerb: string;
  /// Severity bucket — drives the strip's accent color + the drawer
  /// section's left border. Critical → var(--error), high →
  /// var(--severity-high), medium → var(--warning), low →
  /// var(--info).
  severity: 'critical' | 'high' | 'medium' | 'low';
  /// "Why this fires" trace — three sentences naming the specific
  /// signals + the implicit weighting the engine computed. Required
  /// per paper Ch 8 — the question current tooling cannot answer.
  whyTrace: string;
  /// Numeric score for ranking. Higher = more urgent.
  finalScore: number;
  /// The scoring breakdown — useful for debug + the drawer's "why
  /// this ranked above another" affordance.
  scoreBreakdown: {
    baseSeverityScore: number;
    validityUrgencyMultiplier: number;
    timePressureMultiplier: number;
    crossDecisionMultiplier: number;
  };
  /// Direct route the CTA should navigate to.
  ctaHref: string;
  /// Computed-at ISO timestamp — used for cache invalidation.
  computedAt: string;
}

/**
 * Cross-decision pattern detection — output shape from the pattern
 * detector. These are aggregated, then converted to NextMoveRecommendation
 * rows by the main engine via the cross_decision_pattern + lineage_drift
 * categories.
 */
export interface CrossDecisionPattern {
  patternType: 'thesis_cascade' | 'shared_assumption' | 'platform_contagion' | 'lineage_drift';
  /// Plain-language assumption label (e.g. "WAEMU debt-cycle stable
  /// through 2027"). Generated by the LLM augmentation layer for
  /// thesis_cascade + shared_assumption patterns; rule-extracted for
  /// the others.
  assumptionLabel: string;
  /// All containers participating in the pattern. The first id is
  /// the "primary" — the one the strip's CTA routes to.
  containerIds: string[];
  containerNames: string[];
  /// Severity computed from the pattern's blast radius (containers
  /// affected × their composite DQI weights × any fired patterns).
  severity: 'critical' | 'high' | 'medium' | 'low';
  /// Detection confidence. Rule-based patterns = 1.0; LLM-augmented
  /// patterns carry the model's confidence score.
  confidence: number;
  /// Optional: the upstream container whose outcome resolved
  /// differently than forecast (lineage_drift only).
  upstreamContainerId?: string;
  /// Optional: the foundational thesis container (thesis_cascade only).
  thesisContainerId?: string;
}

/**
 * Engine input — the full state the engine reads to produce
 * recommendations. Assembled by the API route from Prisma queries.
 */
export interface EngineInput {
  /// Active containers (status='active', not soft-deleted) for the
  /// scope (org or user).
  containers: EngineContainer[];
  /// All active container links (precedes / spawned_from / depends_on /
  /// parent_of) within the scope.
  links: EngineContainerLink[];
  /// User-priority capture from the most recent constellation visit,
  /// used by the intelligent-antagonist UI to compute divergence vs
  /// the algo's top pick.
  recentUserPriority: { containerId: string | null; capturedAt: string } | null;
  /// User's role for persona-tuned framing.
  persona: 'cso' | 'ma' | 'bizops' | 'pe_vc' | 'other';
  /// Computed-at for cache-key + freshness signal.
  computedAt: Date;
}

export interface EngineContainer {
  id: string;
  kind: 'investment' | 'acquisition' | 'strategic';
  name: string;
  decisionFrame: string | null;
  stageId: string;
  status: string;
  decidedAt: Date | null;
  committeeDate: Date | null;
  compositeDqi: number | null;
  compositeGrade: string | null;
  documentCount: number;
  analyzedDocCount: number;
  recurringBiasCount: number;
  conflictCount: number;
  highSeverityConflictCount: number;
  /// Named patterns fired across the latest analysis on every member
  /// doc — already aggregated server-side by the existing
  /// container-aggregation path.
  namedPatterns: Array<{
    patternLabel: string;
    severity: 'critical' | 'high' | 'medium' | 'low';
    documentCount: number;
  }>;
  /// Whether the container has a closed outcome row.
  hasOutcome: boolean;
  /// Required-doc shortfall (computed against
  /// CONTAINER_MODES[kind].requiredDocs).
  missingRequiredDocs: string[];
  /// Validity class — reads the persisted band on the latest
  /// analysis's judgeOutputs.validityClassification, falls back to
  /// live-compute when absent.
  validityClass: ValidityClass;
  /// Structural assumptions extracted from the latest analysis (the
  /// 'depends_on' Dalio determinants — debt cycle, governance, FX
  /// regime). Used for shared-assumption pattern detection.
  structuralAssumptions: string[];
  /// Capture for the priors-baseline comparison.
  priors: {
    convictionLevel: 'low' | 'medium' | 'high' | 'very_high';
    convictionRationale: string;
    killCriteria: string[];
    capturedAt: string;
  } | null;
}

export interface EngineContainerLink {
  fromId: string;
  toId: string;
  linkType: 'precedes' | 'spawned_from' | 'depends_on' | 'parent_of';
  note: string | null;
}
