/**
 * Cross-document cross-reference agent (3.1 deep).
 *
 * The deal is the atomic decision unit. Looking at any single doc's DQI
 * tells you about that artifact, not the decision. This agent runs
 * across every analyzed document on a Deal and surfaces contradictions
 * between them — numeric ("CIM says 40% CAGR, model assumes 15%"),
 * assumption-level ("memo says regulatory clear, counsel flags CBN
 * ambiguity"), timeline ("close in Q2" vs. "due-diligence into Q3"),
 * and risk-treatment mismatches ("memo treats FX as hedged, model has
 * no hedge line item").
 *
 * Why a separate agent rather than a 12-node-pipeline addition:
 *   - The pipeline runs per-document; this is a one-to-many composition.
 *   - Persisting findings on a `DealCrossReference` row keeps the deal's
 *     read path independent of any single doc's analysis lifecycle.
 *   - Cost is bounded: one call per deal-run, not one per doc.
 *
 * Cost model: ~£0.05–0.15 per run on gemini-3-flash-preview, depending
 * on the combined memo length. The agent caps total input at
 * MAX_TOTAL_INPUT_CHARS so a deal with 10 dense memos doesn't blow
 * the token budget.
 */

import { generateText } from '@/lib/ai/providers/gemini';
import { parseJSON } from '@/lib/utils/json';
import { createLogger } from '@/lib/utils/logger';

const log = createLogger('CrossRefAgent');

export type CrossRefConflictType =
  | 'numeric'
  | 'assumption'
  | 'timeline'
  | 'risk_treatment'
  | 'scope';

export type CrossRefSeverity = 'low' | 'medium' | 'high' | 'critical';

export interface CrossRefClaim {
  /** Document.id this side of the conflict came from. */
  documentId: string;
  /** Document.filename for display. */
  documentName: string;
  /** Short verbatim or near-verbatim excerpt from the doc (≤240 chars). */
  excerpt: string;
}

export interface CrossRefFinding {
  /** Human-readable headline summarising the conflict. */
  summary: string;
  type: CrossRefConflictType;
  severity: CrossRefSeverity;
  /** The two (or more) sides of the conflict — typically 2 entries. */
  claims: CrossRefClaim[];
  /** One-sentence reason this matters for the decision. */
  whyItMatters: string;
  /** One-sentence question the deal team should answer to resolve it. */
  resolutionQuestion: string;
}

export interface CrossRefTruncationReport {
  /** Per-doc cap (chars). */
  perDocCapChars: number;
  /** Total-input cap across all docs (chars). */
  totalCapChars: number;
  /** Total chars actually sent to the model (after truncation). */
  totalCharsSent: number;
  /** Docs whose content was truncated to fit within the per-doc or total cap. */
  truncatedDocs: Array<{
    documentId: string;
    documentName: string;
    originalChars: number;
    sentChars: number;
  }>;
  /** Docs that were excluded entirely because the total cap had been hit. */
  excludedDocs: Array<{ documentId: string; documentName: string; originalChars: number }>;
}

export interface CrossRefRunOutput {
  findings: CrossRefFinding[];
  /**
   * One-paragraph summary the deal hero card can render directly.
   * Generated by the model alongside the findings.
   */
  summary: string;
  documentSnapshot: Array<{
    documentId: string;
    documentName: string;
    analysisId: string;
    overallScore: number;
  }>;
  /**
   * Truncation accounting (2026-04-25 audit fix). The agent caps total
   * input to keep the Gemini call inside its budget envelope; before this
   * field existed, the cap was silent and an 80-200-page CIM would
   * silently lose its synergy table to truncation, producing a
   * "no conflicts" reading the deal team would trust. The card surfaces
   * any truncation as a visible banner so the reader knows the scan is
   * partial.
   */
  truncationReport: CrossRefTruncationReport;
}

export interface CrossRefInputDoc {
  documentId: string;
  documentName: string;
  analysisId: string;
  overallScore: number;
  /** Decrypted memo content. */
  content: string;
  /** Top biases the per-doc audit flagged — helps the agent triangulate. */
  topBiases?: Array<{ biasType: string; severity?: string | null }>;
}

// Caps lifted 2026-04-25 from 60K/12K to 150K/25K (gemini-3-flash-preview
// has a 1M+ token window — ~50K tokens at 150K chars is well inside it).
// A 25K-char per-doc cap fits ~50 pages of dense CIM content, which is
// enough for the synergy / unit-economics / risk sections most deals turn
// on. Beyond 150K total, the next step is chunked multi-pass which is
// flagged for the cross-ref capability follow-up.
const MAX_TOTAL_INPUT_CHARS = 150_000;
const MAX_PER_DOC_CHARS = 25_000;

function truncate(text: string, max: number): string {
  if (!text) return '';
  if (text.length <= max) return text;
  return text.slice(0, max) + '\n\n[…truncated for cross-reference scan…]';
}

function buildCrossRefPrompt(docs: CrossRefInputDoc[]): string {
  const blocks = docs
    .map((d, idx) => {
      const biasLine = d.topBiases?.length
        ? `Top biases on this doc: ${d.topBiases
            .slice(0, 5)
            .map(b => `${b.biasType}${b.severity ? ` (${b.severity})` : ''}`)
            .join(', ')}`
        : 'Top biases on this doc: none surfaced.';
      return `--- DOC ${idx + 1} ---
Document ID: ${d.documentId}
Filename: ${d.documentName}
Per-doc DQI: ${Math.round(d.overallScore)}/100
${biasLine}

CONTENT:
${truncate(d.content, MAX_PER_DOC_CHARS)}
--- END DOC ${idx + 1} ---`;
    })
    .join('\n\n');

  return `You are Decision Intel's CROSS-REFERENCE AGENT.

You are given ${docs.length} documents that all live under a single deal (or strategic decision package). Each document was already audited individually for cognitive biases and noise. Your job is DIFFERENT: surface the CONFLICTS BETWEEN the documents — places where they disagree about a number, an assumption, a timeline, or how a risk is treated.

The deal team will read your findings BEFORE they make the decision, so:
- Three well-evidenced conflicts beat ten weak ones.
- Quote the specific text from each doc that anchors the conflict.
- Be specific about what the conflict means for the decision, not just that one exists.

Conflict types:
- numeric          — different numbers for the same quantity (CAGR, ticket, headcount, market size, IRR)
- assumption       — different read of the same underlying assumption (regulatory clear vs. ambiguous, market mature vs. nascent)
- timeline         — different read of when something will happen (close, integration milestone, exit)
- risk_treatment   — one doc treats a risk as hedged/mitigated; another exposes it as live
- scope            — one doc's scope contradicts another's (e.g. memo says "domestic only", CIM mentions cross-border revenue)

Severity:
- critical  — the deal cannot proceed without reconciling
- high      — a steering-committee question, must be resolved before vote
- medium    — needs an answer in the next iteration
- low       — minor inconsistency, worth noting

Return ONLY valid JSON matching this exact shape (no markdown, no prose):
{
  "summary": "string — one paragraph (max 220 chars) summarising the deal-level reading",
  "findings": [
    {
      "summary": "string — one sentence headline (max 140 chars)",
      "type": "numeric | assumption | timeline | risk_treatment | scope",
      "severity": "low | medium | high | critical",
      "claims": [
        {
          "documentId": "string — must match one of the IDs above",
          "documentName": "string — copy the filename",
          "excerpt": "string — short quote or paraphrase, max 240 chars"
        }
      ],
      "whyItMatters": "string — one sentence on the impact for the decision",
      "resolutionQuestion": "string — one question the team should answer next"
    }
  ]
}

Rules:
- Only flag conflicts that are real and grounded in the text. Speculation is not a conflict.
- Do NOT flag "different focus" or "complementary detail" — they are not conflicts.
- Each finding must have at least 2 claims from at least 2 distinct documents.
- The same document may appear in multiple findings.
- If there are no meaningful conflicts, return { "summary": "No cross-document conflicts detected on the available material.", "findings": [] }.

DOCUMENTS:
${blocks}`;
}

/**
 * Run the cross-reference agent across the supplied analyzed docs.
 * Returns a structured result the caller can persist to DealCrossReference.
 *
 * Caller is responsible for:
 *   - Fetching the documents (with decrypted content) and their latest analyses
 *   - Persisting the result to DealCrossReference
 *   - RBAC (visibility) — the API endpoint that wraps this MUST verify the
 *     caller can read every doc in the input set.
 */
export async function runCrossReferenceAgent(docs: CrossRefInputDoc[]): Promise<CrossRefRunOutput> {
  if (docs.length < 2) {
    return {
      findings: [],
      summary: 'Cross-reference requires at least two analyzed documents on the deal.',
      documentSnapshot: docs.map(d => ({
        documentId: d.documentId,
        documentName: d.documentName,
        analysisId: d.analysisId,
        overallScore: d.overallScore,
      })),
      truncationReport: {
        perDocCapChars: MAX_PER_DOC_CHARS,
        totalCapChars: MAX_TOTAL_INPUT_CHARS,
        totalCharsSent: 0,
        truncatedDocs: [],
        excludedDocs: [],
      },
    };
  }

  // Cap total input — for a 12-doc deal with dense CIMs this can balloon.
  // We track per-doc truncation + total exclusion so the UI can show a
  // visible banner; the silent truncation that shipped before 2026-04-25
  // produced "no conflicts found" readings that ignored entire CIM
  // sections (Marcus's persona-audit catch).
  let totalChars = 0;
  const capped: CrossRefInputDoc[] = [];
  const truncatedDocs: CrossRefTruncationReport['truncatedDocs'] = [];
  const excludedDocs: CrossRefTruncationReport['excludedDocs'] = [];
  for (const d of docs) {
    const originalLen = (d.content || '').length;
    if (totalChars >= MAX_TOTAL_INPUT_CHARS) {
      excludedDocs.push({
        documentId: d.documentId,
        documentName: d.documentName,
        originalChars: originalLen,
      });
      continue;
    }
    const remainingTotal = MAX_TOTAL_INPUT_CHARS - totalChars;
    const perDocBudget = Math.min(MAX_PER_DOC_CHARS, remainingTotal);
    if (originalLen > perDocBudget) {
      const sentLen = Math.max(2_000, perDocBudget);
      const sentContent = truncate(d.content || '', sentLen);
      capped.push({ ...d, content: sentContent });
      totalChars += sentContent.length;
      truncatedDocs.push({
        documentId: d.documentId,
        documentName: d.documentName,
        originalChars: originalLen,
        sentChars: sentContent.length,
      });
    } else {
      capped.push(d);
      totalChars += originalLen;
    }
  }
  const truncationReport: CrossRefTruncationReport = {
    perDocCapChars: MAX_PER_DOC_CHARS,
    totalCapChars: MAX_TOTAL_INPUT_CHARS,
    totalCharsSent: totalChars,
    truncatedDocs,
    excludedDocs,
  };

  const prompt = buildCrossRefPrompt(capped);

  const result = await generateText(prompt, {
    model: 'gemini-3-flash-preview',
    temperature: 0.15,
    maxTokens: 2400,
  });

  const parsed = parseJSON(result.text) as {
    summary?: string;
    findings?: CrossRefFinding[];
  } | null;

  const validIds = new Set(capped.map(d => d.documentId));
  const findings: CrossRefFinding[] = Array.isArray(parsed?.findings)
    ? parsed!.findings
        .map(f => ({
          summary: String(f.summary ?? '')
            .trim()
            .slice(0, 240),
          type: normaliseType(f.type),
          severity: normaliseSeverity(f.severity),
          whyItMatters: String(f.whyItMatters ?? '')
            .trim()
            .slice(0, 280),
          resolutionQuestion: String(f.resolutionQuestion ?? '')
            .trim()
            .slice(0, 280),
          claims: Array.isArray(f.claims)
            ? f.claims
                .map(c => ({
                  documentId: String(c.documentId ?? '').trim(),
                  documentName: String(c.documentName ?? '').trim(),
                  excerpt: String(c.excerpt ?? '')
                    .trim()
                    .slice(0, 280),
                }))
                .filter(c => validIds.has(c.documentId) && c.excerpt.length > 0)
            : [],
        }))
        .filter(
          f =>
            f.summary.length > 0 &&
            // At least 2 claims from ≥2 distinct docs
            f.claims.length >= 2 &&
            new Set(f.claims.map(c => c.documentId)).size >= 2
        )
    : [];

  log.info(
    `cross-ref complete: ${findings.length} findings across ${capped.length} docs (${totalChars.toLocaleString()} chars)`
  );

  return {
    findings,
    summary:
      typeof parsed?.summary === 'string' && parsed.summary.trim().length > 0
        ? parsed.summary.trim().slice(0, 320)
        : findings.length === 0
          ? 'No cross-document conflicts detected on the available material.'
          : `${findings.length} cross-document conflict${findings.length !== 1 ? 's' : ''} flagged across ${capped.length} docs.`,
    documentSnapshot: capped.map(d => ({
      documentId: d.documentId,
      documentName: d.documentName,
      analysisId: d.analysisId,
      overallScore: d.overallScore,
    })),
    truncationReport,
  };
}

function normaliseType(v: unknown): CrossRefConflictType {
  const s = String(v ?? '').toLowerCase();
  if (s === 'numeric') return 'numeric';
  if (s === 'timeline') return 'timeline';
  if (s === 'risk_treatment' || s === 'risk-treatment' || s === 'risk') return 'risk_treatment';
  if (s === 'scope') return 'scope';
  return 'assumption';
}

function normaliseSeverity(v: unknown): CrossRefSeverity {
  const s = String(v ?? '').toLowerCase();
  if (s === 'critical') return 'critical';
  if (s === 'high' || s === 'severe') return 'high';
  if (s === 'medium' || s === 'moderate') return 'medium';
  return 'low';
}
