import jsPDF from 'jspdf';
import { formatBiasName } from '@/lib/utils/labels';
import type { ReportAnalysisData, ReportBiasInstance, SimulationData } from './pdf-generator';

/** Projected-impact data for page 2's counterfactual section. Supplied by
 *  the caller — the board generator itself is side-effect-free and does
 *  not fetch. When null/undefined, the PROJECTED IMPACT section is
 *  omitted rather than shown with fabricated numbers. */
export interface BoardCounterfactualTop {
  biasType: string;
  expectedImprovement: number; // percentage points (e.g. 18.5 → "+18.5pp")
  impactUsd?: number; // optional dollar estimate
  confidence?: number; // 0–1
  similarDecisionsCount?: number;
}

/** Per-org branding for the Board Report PDF (2026-04-25 audit fix —
 *  Elena's "stamped 'Generated by Decision Intel · R²F' reads like
 *  marketing collateral, not internal control artefact" catch). When
 *  populated, the footer carries the customer org name + retention
 *  policy footer line, and a GC signature block is appended to the last
 *  page. Logo upload is deferred to the per-org settings UI; the
 *  generator accepts an optional base64 PNG/JPEG today so callers that
 *  already have one (e.g. an enterprise admin who pasted in a Settings
 *  → Brand surface) can pass it through. */
export interface BoardReportBranding {
  /** Customer organisation name (e.g. "Acme Inc."). Renders in the
   *  footer ahead of the Decision Intel attribution. */
  orgName?: string;
  /** GC name + title for the signature block on the final page. */
  gcName?: string;
  gcTitle?: string;
  /** Optional bar number / regulator-of-record reference shown next to
   *  the GC signature line. */
  gcRegistration?: string;
  /** Org-level retention policy statement appended to the footer. Free
   *  text, ≤140 chars (e.g. "Retention: 12 months from upload."). */
  retentionPolicy?: string;
  /** Base64-encoded image (PNG/JPEG) for the page-one cover logo.
   *  Optional; the generator skips the logo when not supplied. */
  logoBase64?: string;
}

interface BoardReportData {
  filename: string;
  analysis: ReportAnalysisData & {
    mitigations?: Array<{ biasType?: string; recommendation?: string; suggestion?: string }>;
  };
  /** Top counterfactual scenario (highest expected improvement). When
   *  supplied, renders a PROJECTED IMPACT section on page 2. Optional —
   *  the caller fetches this from /api/counterfactual and passes it
   *  through; null when the endpoint returned no positive scenarios. */
  counterfactualTop?: BoardCounterfactualTop | null;
  /** When true, stamps a diagonal "CONFIDENTIAL" watermark on every
   *  page and prefixes the footer with "CONFIDENTIAL — ". Intended for
   *  CSOs forwarding the report internally to audit / steering /
   *  board committees who need a visible classification marker. */
  confidential?: boolean;
  /** Per-org branding overrides. When omitted, the report renders with
   *  the default Decision Intel attribution only. */
  branding?: BoardReportBranding;
}

// A4 layout constants. Margins widened from 20mm to 22mm 2026-04-24 for
// breathing room — the board report was reading as "dense" per the
// enterprise-polish audit. TEXT_W drops from 170 to 166 in consequence.
const PAGE_W = 210;
const MARGIN_L = 22;
const MARGIN_R = 22;
const TEXT_W = PAGE_W - MARGIN_L - MARGIN_R;

const SEVERITY_ORDER: Record<string, number> = {
  critical: 0,
  high: 1,
  medium: 2,
  low: 3,
};

const SEVERITY_RGB: Record<string, [number, number, number]> = {
  critical: [220, 38, 38],
  high: [234, 88, 12],
  medium: [234, 179, 8],
  low: [59, 130, 246],
};

const MAX_SUMMARY_CHARS = 500;
const MAX_EXCERPT_CHARS = 180;
const MAX_MITIGATION_CHARS = 400;
const MAX_TITLE_CHARS = 70;

function truncate(text: string, max: number): string {
  if (!text) return '';
  const clean = text.trim();
  return clean.length > max ? clean.slice(0, max - 1).trimEnd() + '…' : clean;
}

function gradeFromScore(score: number): string {
  if (score >= 85) return 'A';
  if (score >= 70) return 'B';
  if (score >= 55) return 'C';
  if (score >= 40) return 'D';
  return 'F';
}

function interpretGrade(grade: string): string {
  switch (grade) {
    case 'A':
      return 'Board-ready. Strong reasoning across the stack.';
    case 'B':
      return 'Mostly solid. Address the flagged biases before the vote.';
    case 'C':
      return 'Mixed. Several reasoning gaps need explicit treatment.';
    case 'D':
      return 'Weak. Rework required before the committee reviews.';
    default:
      return 'Critical. Reset the memo before re-circulating.';
  }
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/\.[^.]+$/, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 60);
}

export class BoardReportGenerator {
  private doc: jsPDF;

  constructor() {
    this.doc = new jsPDF();
  }

  public generateReport(data: BoardReportData) {
    const { filename, analysis, confidential = false, counterfactualTop, branding } = data;
    const title = truncate(filename.replace(/\.[^.]+$/, ''), MAX_TITLE_CHARS);
    const allBiases = [...(analysis.biases || [])].sort(
      (a, b) =>
        (SEVERITY_ORDER[a.severity?.toLowerCase()] ?? 4) -
        (SEVERITY_ORDER[b.severity?.toLowerCase()] ?? 4)
    );
    const topBiases = allBiases.slice(0, 3);
    const remainingBiases = allBiases.slice(3);

    this.drawPageOne({ title, analysis, topBiases, branding });
    this.doc.addPage();
    this.drawPageTwo({ analysis, topBiases, counterfactualTop });
    // Additional-risks page(s) — biases 4+ paginate here instead of being
    // silently dropped. Dropping risks from a board-committee artifact is
    // not acceptable for Sankore-sized investment committee memos, which
    // can easily flag 6–8 biases.
    if (remainingBiases.length > 0) {
      this.doc.addPage();
      this.drawAdditionalRisks(remainingBiases);
    }
    if (branding?.gcName || branding?.gcTitle) {
      this.drawSignatureBlock(branding);
    }
    if (confidential) this.drawConfidentialWatermark();
    this.drawFooter(confidential, branding);

    const classified = confidential ? '-confidential' : '';
    this.doc.save(
      `board-report-${slugify(filename)}-${new Date().toISOString().slice(0, 10)}${classified}.pdf`
    );
  }

  private drawPageOne({
    title,
    analysis,
    topBiases,
    branding,
  }: {
    title: string;
    analysis: ReportAnalysisData;
    topBiases: ReportBiasInstance[];
    branding?: BoardReportBranding;
  }) {
    // Accent band
    this.doc.setFillColor(22, 163, 74);
    this.doc.rect(0, 0, PAGE_W, 6, 'F');

    // Optional org logo on the cover. Renders top-right when supplied;
    // jspdf accepts base64 PNG/JPEG via addImage. Errors swallowed because
    // a malformed image must not block the rest of the report.
    if (branding?.logoBase64) {
      try {
        // 18mm tall, max 36mm wide; jspdf preserves aspect ratio when the
        // second size arg is left undefined (we pass 0 to mean "auto").
        this.doc.addImage(branding.logoBase64, 'PNG', PAGE_W - MARGIN_R - 36, 10, 36, 0);
      } catch {
        /* malformed logo — skip silently, the rest of the report stands */
      }
    }

    // Header
    this.doc.setTextColor(5, 5, 5);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(10);
    this.doc.text('BOARD-READY DECISION AUDIT', MARGIN_L, 18);
    if (branding?.orgName) {
      this.doc.setFont('helvetica', 'normal');
      this.doc.setFontSize(9);
      this.doc.setTextColor(120, 120, 120);
      this.doc.text(branding.orgName, MARGIN_L, 24);
    }
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(9);
    this.doc.setTextColor(120, 120, 120);
    // When a logo is rendered top-right, the date moves down to avoid overlap.
    const dateY = branding?.logoBase64 ? 32 : 18;
    this.doc.text(new Date().toLocaleDateString(), PAGE_W - MARGIN_R, dateY, {
      align: 'right',
    });

    // Title
    this.doc.setTextColor(5, 5, 5);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(18);
    const titleLines = this.doc.splitTextToSize(title, TEXT_W);
    this.doc.text(titleLines, MARGIN_L, 32);
    const titleHeight = titleLines.length * 8;

    // DQI card
    const cardY = 32 + titleHeight + 4;
    const score = Math.round(analysis.overallScore || 0);
    const grade = gradeFromScore(score);
    this.drawDqiCard(cardY, score, grade);

    // Executive summary — line-height loosened 5 → 5.8 for breathing room.
    let yPos = cardY + 44;
    this.drawSectionHeading('EXECUTIVE SUMMARY', yPos);
    yPos += 8;
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(10.5);
    this.doc.setTextColor(40, 40, 40);
    const summaryText = truncate(analysis.summary || 'No summary generated.', MAX_SUMMARY_CHARS);
    const summaryLines = this.doc.splitTextToSize(summaryText, TEXT_W);
    this.doc.text(summaryLines, MARGIN_L, yPos);
    yPos += summaryLines.length * 5.8 + 9;

    // Top 3 biases — label is now dynamic ("TOP COGNITIVE RISKS") so it
    // stays accurate whether there are 0, 1, 2, 3, or 3+ biases overall.
    const heading =
      topBiases.length === 3
        ? 'TOP 3 COGNITIVE RISKS'
        : topBiases.length === 0
          ? 'COGNITIVE RISKS'
          : `TOP ${topBiases.length} COGNITIVE RISK${topBiases.length === 1 ? '' : 'S'}`;
    this.drawSectionHeading(heading, yPos);
    yPos += 8;
    if (topBiases.length === 0) {
      this.doc.setFont('helvetica', 'italic');
      this.doc.setFontSize(10);
      this.doc.setTextColor(90, 130, 90);
      this.doc.text('No significant biases detected.', MARGIN_L, yPos);
    } else {
      for (const bias of topBiases) {
        yPos = this.drawBiasRow(bias, yPos);
        if (yPos > 260) break;
      }
    }
  }

  private drawDqiCard(y: number, score: number, grade: string) {
    // Card background — width adjusted from 170 to TEXT_W (166) for the
    // new margin system.
    this.doc.setDrawColor(220, 220, 220);
    this.doc.setFillColor(250, 250, 250);
    this.doc.roundedRect(MARGIN_L, y, TEXT_W, 36, 3, 3, 'FD');

    // Score
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(28);
    this.doc.setTextColor(22, 163, 74);
    this.doc.text(`${score}`, MARGIN_L + 10, y + 23);

    this.doc.setFontSize(10);
    this.doc.setTextColor(100, 100, 100);
    this.doc.text('/100', MARGIN_L + 36, y + 23);

    // Grade pill
    this.doc.setFillColor(22, 163, 74);
    this.doc.roundedRect(MARGIN_L + 55, y + 11, 18, 14, 2, 2, 'F');
    this.doc.setTextColor(255, 255, 255);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(12);
    this.doc.text(grade, MARGIN_L + 64, y + 21, { align: 'center' });

    // Interpretation
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(9.5);
    this.doc.setTextColor(60, 60, 60);
    this.doc.text('DECISION QUALITY INDEX', MARGIN_L + 80, y + 13);
    this.doc.setFontSize(9);
    this.doc.setTextColor(80, 80, 80);
    const interp = this.doc.splitTextToSize(interpretGrade(grade), TEXT_W - 80);
    this.doc.text(interp, MARGIN_L + 80, y + 21);
  }

  private drawBiasRow(bias: ReportBiasInstance, startY: number): number {
    const severity = (bias.severity || 'medium').toLowerCase();
    const color = SEVERITY_RGB[severity] || [100, 100, 100];
    const name = formatBiasName(bias.biasType);
    const rawExcerpt = bias.excerpt || bias.explanation || '';
    const wasTruncated = rawExcerpt.trim().length > MAX_EXCERPT_CHARS;
    const excerpt = truncate(rawExcerpt, MAX_EXCERPT_CHARS);

    // Severity stripe — widened 2mm → 3mm so it survives anti-aliasing
    // in common PDF readers (Preview, Acrobat, Sumatra) and reads as a
    // clear severity indicator rather than a hair-thin line.
    this.doc.setFillColor(color[0], color[1], color[2]);
    this.doc.rect(MARGIN_L, startY - 4, 3, 24, 'F');

    // Name + severity
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(11);
    this.doc.setTextColor(10, 10, 10);
    this.doc.text(name, MARGIN_L + 7, startY + 2);

    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(8);
    this.doc.setTextColor(color[0], color[1], color[2]);
    this.doc.text(severity.toUpperCase(), PAGE_W - MARGIN_R, startY + 2, {
      align: 'right',
    });

    // "Detected in memo" micro-caption — tells the reader this is a
    // quote from THEIR memo, not a generated summary. Matters when the
    // excerpt gets forwarded to audit committee members who weren't in
    // the upload session.
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(7.5);
    this.doc.setTextColor(140, 140, 140);
    this.doc.text('DETECTED IN MEMO', MARGIN_L + 7, startY + 6);

    // Excerpt — line-height loosened 4.5 → 5 for breathing room.
    // Trailing ellipsis already added by truncate(); suffix marker
    // signals to the reader that there's more context on page 3+.
    this.doc.setFont('helvetica', 'italic');
    this.doc.setFontSize(9.5);
    this.doc.setTextColor(70, 70, 70);
    const excerptLines = this.doc.splitTextToSize(`"${excerpt}"`, TEXT_W - 10);
    this.doc.text(excerptLines, MARGIN_L + 7, startY + 11);

    let nextY = startY + 11 + excerptLines.length * 5 + 5;

    // If we truncated, add a subtle context hint under the quote.
    if (wasTruncated) {
      this.doc.setFont('helvetica', 'italic');
      this.doc.setFontSize(7.5);
      this.doc.setTextColor(150, 150, 150);
      this.doc.text('Full passage available in the analysis detail.', MARGIN_L + 7, nextY);
      nextY += 4;
    }

    return nextY + 2;
  }

  private drawPageTwo({
    analysis,
    topBiases,
    counterfactualTop,
  }: {
    analysis: BoardReportData['analysis'];
    topBiases: ReportBiasInstance[];
    counterfactualTop?: BoardCounterfactualTop | null;
  }) {
    // Accent band
    this.doc.setFillColor(22, 163, 74);
    this.doc.rect(0, 0, PAGE_W, 6, 'F');

    this.doc.setTextColor(5, 5, 5);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(10);
    this.doc.text('BOARD-READY DECISION AUDIT', MARGIN_L, 18);

    // Simulated CEO question
    let yPos = 32;
    this.drawSectionHeading('SIMULATED CEO QUESTION', yPos);
    yPos += 8;
    const ceoQuestion = extractTopCeoQuestion(analysis.simulation);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(11);
    this.doc.setTextColor(30, 30, 30);
    const ceoLines = this.doc.splitTextToSize(ceoQuestion, TEXT_W);
    this.doc.text(ceoLines, MARGIN_L, yPos);
    yPos += ceoLines.length * 5.8 + 12;

    // Recommended mitigation
    this.drawSectionHeading('RECOMMENDED MITIGATION', yPos);
    yPos += 8;
    const mitigationText = extractTopMitigation(topBiases, analysis.mitigations);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(10.5);
    this.doc.setTextColor(40, 40, 40);
    const mitigationLines = this.doc.splitTextToSize(
      truncate(mitigationText, MAX_MITIGATION_CHARS),
      TEXT_W
    );
    this.doc.text(mitigationLines, MARGIN_L, yPos);
    yPos += mitigationLines.length * 5.5 + 12;

    // Projected impact — counterfactual ROI. Rendered only when the
    // caller supplied a scenario (silent skip when null, never
    // fabricated). Gives the committee a forward-looking "what if we
    // accepted the mitigation" anchor rather than pure risk framing.
    if (counterfactualTop) {
      this.drawSectionHeading('PROJECTED IMPACT IF MITIGATION IS APPLIED', yPos);
      yPos += 8;
      this.doc.setFont('helvetica', 'bold');
      this.doc.setFontSize(16);
      this.doc.setTextColor(22, 163, 74);
      const improvement = counterfactualTop.expectedImprovement;
      const headline = `+${improvement.toFixed(1)}pp DQI uplift`;
      this.doc.text(headline, MARGIN_L, yPos);
      yPos += 8;

      this.doc.setFont('helvetica', 'normal');
      this.doc.setFontSize(10);
      this.doc.setTextColor(60, 60, 60);
      const addressedBy = `Addresses: ${formatBiasName(counterfactualTop.biasType)}`;
      this.doc.text(addressedBy, MARGIN_L, yPos);
      yPos += 5;

      const extras: string[] = [];
      if (typeof counterfactualTop.impactUsd === 'number' && counterfactualTop.impactUsd > 0) {
        const usdText =
          counterfactualTop.impactUsd >= 1_000_000
            ? `$${(counterfactualTop.impactUsd / 1_000_000).toFixed(1)}M`
            : `$${Math.round(counterfactualTop.impactUsd / 1000)}k`;
        extras.push(`Estimated impact: ${usdText}`);
      }
      if (typeof counterfactualTop.confidence === 'number') {
        extras.push(`Confidence: ${Math.round(counterfactualTop.confidence * 100)}%`);
      }
      if (
        typeof counterfactualTop.similarDecisionsCount === 'number' &&
        counterfactualTop.similarDecisionsCount > 0
      ) {
        extras.push(
          `Calibrated against ${counterfactualTop.similarDecisionsCount} similar decisions`
        );
      }
      if (extras.length > 0) {
        this.doc.setFont('helvetica', 'italic');
        this.doc.setFontSize(9);
        this.doc.setTextColor(100, 100, 100);
        this.doc.text(extras.join('     ·     '), MARGIN_L, yPos);
      }
    }
  }

  /** Additional-risks page. Renders biases beyond the top-3. Uses the
   *  same drawBiasRow helper so the layout matches page 1 exactly.
   *  Paginates automatically if the list is long enough to overflow. */
  private drawAdditionalRisks(biases: ReportBiasInstance[]) {
    let yPos = this.drawAdditionalRisksHeader(/* isContinuation */ false);
    const totalCount = biases.length;
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(9.5);
    this.doc.setTextColor(80, 80, 80);
    this.doc.text(
      `${totalCount} additional cognitive risk${totalCount === 1 ? '' : 's'} flagged beyond the top 3. Listed in severity order.`,
      MARGIN_L,
      yPos
    );
    yPos += 10;

    for (const bias of biases) {
      // Estimate the row height so we can paginate cleanly instead of
      // letting a row overflow the bottom margin.
      const rawExcerpt = bias.excerpt || bias.explanation || '';
      const excerpt = truncate(rawExcerpt, MAX_EXCERPT_CHARS);
      const estimatedLines = this.doc.splitTextToSize(`"${excerpt}"`, TEXT_W - 10).length;
      const rowEstHeight = 11 + estimatedLines * 5 + 10;
      if (yPos + rowEstHeight > 275) {
        this.doc.addPage();
        yPos = this.drawAdditionalRisksHeader(/* isContinuation */ true);
      }
      yPos = this.drawBiasRow(bias, yPos);
    }
  }

  private drawAdditionalRisksHeader(isContinuation: boolean): number {
    this.doc.setFillColor(22, 163, 74);
    this.doc.rect(0, 0, PAGE_W, 6, 'F');
    this.doc.setTextColor(5, 5, 5);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(10);
    this.doc.text('BOARD-READY DECISION AUDIT', MARGIN_L, 18);
    let yPos = 32;
    this.drawSectionHeading(
      isContinuation ? 'ADDITIONAL COGNITIVE RISKS (cont.)' : 'ADDITIONAL COGNITIVE RISKS',
      yPos
    );
    yPos += 10;
    return yPos;
  }

  private drawSectionHeading(label: string, y: number) {
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(9);
    this.doc.setTextColor(120, 120, 120);
    this.doc.text(label, MARGIN_L, y);
    this.doc.setDrawColor(220, 220, 220);
    this.doc.line(MARGIN_L, y + 2, PAGE_W - MARGIN_R, y + 2);
  }

  private drawFooter(confidential: boolean = false, branding?: BoardReportBranding) {
    const pages = this.doc.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      this.doc.setPage(i);
      this.doc.setFont('helvetica', confidential ? 'bold' : 'normal');
      this.doc.setFontSize(8);
      if (confidential) this.doc.setTextColor(190, 60, 60);
      else this.doc.setTextColor(150, 150, 150);
      const segments: string[] = [];
      if (confidential) segments.push('CONFIDENTIAL');
      if (branding?.orgName) segments.push(branding.orgName);
      segments.push('Generated by Decision Intel · R²F');
      segments.push(new Date().toLocaleDateString());
      segments.push(`Page ${i}/${pages}`);
      this.doc.text(segments.join(' · '), PAGE_W / 2, 290, { align: 'center' });
      if (branding?.retentionPolicy) {
        this.doc.setFont('helvetica', 'normal');
        this.doc.setFontSize(7);
        this.doc.setTextColor(160, 160, 160);
        this.doc.text(
          truncate(branding.retentionPolicy, 140),
          PAGE_W / 2,
          294,
          { align: 'center' }
        );
      }
    }
  }

  /** GC signature block on the final page. Renders only when the
   *  caller passes branding.gcName or branding.gcTitle. The block
   *  occupies the bottom-third of whatever page is currently in
   *  context — call it AFTER all content pages are drawn. */
  private drawSignatureBlock(branding: BoardReportBranding) {
    // Append to the last page (or add a new one if there's no room
    // — we leave 70mm headroom above the footer for the block).
    const pages = this.doc.getNumberOfPages();
    this.doc.setPage(pages);
    let y = 230;
    // No reliable cursor on jspdf; place at fixed Y. If the page
    // already has dense content above, the block still renders cleanly
    // at this Y because the footer is at 290 (60mm clearance).
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(9);
    this.doc.setTextColor(80, 80, 80);
    this.doc.text('REVIEWED AND SIGNED', MARGIN_L, y);
    this.doc.setDrawColor(200, 200, 200);
    this.doc.line(MARGIN_L, y + 2, PAGE_W - MARGIN_R, y + 2);
    y += 18;
    this.doc.setDrawColor(40, 40, 40);
    this.doc.line(MARGIN_L, y, MARGIN_L + 80, y);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8);
    this.doc.setTextColor(120, 120, 120);
    this.doc.text('Signature', MARGIN_L, y + 4);
    if (branding.gcName) {
      this.doc.setFont('helvetica', 'bold');
      this.doc.setFontSize(10);
      this.doc.setTextColor(40, 40, 40);
      this.doc.text(branding.gcName, MARGIN_L, y + 12);
    }
    if (branding.gcTitle) {
      this.doc.setFont('helvetica', 'normal');
      this.doc.setFontSize(9);
      this.doc.setTextColor(120, 120, 120);
      this.doc.text(branding.gcTitle, MARGIN_L, y + 17);
    }
    if (branding.gcRegistration) {
      this.doc.setFont('helvetica', 'normal');
      this.doc.setFontSize(8);
      this.doc.setTextColor(150, 150, 150);
      this.doc.text(branding.gcRegistration, MARGIN_L, y + 22);
    }
    // Date column on the right
    this.doc.setDrawColor(40, 40, 40);
    this.doc.line(PAGE_W - MARGIN_R - 60, y, PAGE_W - MARGIN_R, y);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8);
    this.doc.setTextColor(120, 120, 120);
    this.doc.text('Date', PAGE_W - MARGIN_R - 60, y + 4);
  }

  /** Diagonal CONFIDENTIAL watermark on every page. Uses the GState
   *  opacity channel so the mark is legible but doesn't fight the
   *  content for attention. Faint red so it reads as a classification
   *  marker, not decorative text. */
  private drawConfidentialWatermark() {
    const pages = this.doc.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      this.doc.setPage(i);
      const gState = this.doc.GState({ opacity: 0.12 });
      this.doc.setGState(gState);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setFontSize(80);
      this.doc.setTextColor(220, 38, 38);
      // 210×297 is A4; rotate -38° around the centre to match the
      // classic diagonal stamp convention.
      this.doc.text('CONFIDENTIAL', PAGE_W / 2, 160, {
        align: 'center',
        angle: 38,
      });
      // Reset opacity so subsequent drawing (footer, etc.) is not
      // accidentally faded.
      this.doc.setGState(this.doc.GState({ opacity: 1 }));
    }
  }
}

function extractTopCeoQuestion(simulation: SimulationData | undefined): string {
  if (!simulation?.twins || simulation.twins.length === 0) {
    return 'No simulated questions yet — re-run analysis to generate.';
  }
  // Pick the rationale from the twin with the lowest-confidence approval or a rejection.
  const sorted = [...simulation.twins].sort((a, b) => {
    const aScore = (a.vote === 'REJECT' ? 0 : 1) * 100 + a.confidence;
    const bScore = (b.vote === 'REJECT' ? 0 : 1) * 100 + b.confidence;
    return aScore - bScore;
  });
  const top = sorted[0];
  return `From ${top.name} (${top.role}): "${top.rationale}"`;
}

function extractTopMitigation(
  topBiases: ReportBiasInstance[],
  mitigations: BoardReportData['analysis']['mitigations']
): string {
  if (topBiases.length === 0) {
    return 'No material biases flagged. Proceed to the committee with the standard decision template.';
  }
  const primary = topBiases[0];
  if (mitigations && mitigations.length > 0) {
    const matched = mitigations.find(m => m.biasType === primary.biasType);
    const text = matched?.recommendation || matched?.suggestion;
    if (text) return text;
  }
  if (primary.suggestion) return primary.suggestion;
  if (primary.explanation) return primary.explanation;
  return `Address ${formatBiasName(primary.biasType)} directly before the vote — request an independent review of the reasoning chain and capture the dissent in the board packet.`;
}
