interface MarkdownReportData {
  filename: string;
  uploadedAt: string;
  overallScore: number;
  noiseScore: number;
  summary: string;
  biases?: Array<{
    biasType: string;
    severity: string;
    excerpt: string;
    explanation: string;
    suggestion: string;
  }>;
  factCheck?: {
    score: number;
    verifications?: Array<{
      claim: string;
      verdict: string;
      explanation: string;
    }>;
  };
  compliance?: {
    status: string;
    riskScore: number;
    summary: string;
    regulations?: Array<{ name: string; status: string; description: string }>;
  };
  swotAnalysis?: {
    strengths: string[];
    weaknesses: string[];
    opportunities: string[];
    threats: string[];
    strategicAdvice: string;
  };
  simulation?: {
    overallVerdict: string;
    twins?: Array<{
      name: string;
      role: string;
      vote: string;
      confidence: number;
      rationale: string;
    }>;
  };
  noiseStats?: { mean: number; stdDev: number; variance: number };
  logicalAnalysis?: {
    score: number;
    fallacies?: Array<{ name: string; severity: string; explanation: string }>;
  };
}

/**
 * Generate a Markdown report from analysis data.
 */
export function generateMarkdownReport(data: MarkdownReportData): string {
  const lines: string[] = [];

  lines.push(`# Decision Audit Report: ${data.filename}`);
  lines.push('');
  lines.push(`> Generated by Decision Intel on ${new Date(data.uploadedAt).toLocaleDateString()}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Executive Summary
  lines.push('## Executive Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Decision Quality | **${Math.round(data.overallScore)}/100** |`);
  lines.push(`| Noise Score | ${Math.round(data.noiseScore)}% |`);
  lines.push(`| Biases Detected | ${data.biases?.length || 0} |`);
  if (data.factCheck) lines.push(`| Fact-Check Score | ${data.factCheck.score}/100 |`);
  if (data.compliance) lines.push(`| Compliance | ${data.compliance.status} (risk: ${data.compliance.riskScore}) |`);
  lines.push('');
  lines.push(data.summary);
  lines.push('');

  // Biases
  if (data.biases && data.biases.length > 0) {
    lines.push('## Cognitive Biases Detected');
    lines.push('');
    for (const bias of data.biases) {
      lines.push(`### ${bias.biasType} (\`${bias.severity}\`)`);
      lines.push('');
      lines.push(`> "${bias.excerpt}"`);
      lines.push('');
      lines.push(`**Analysis:** ${bias.explanation}`);
      lines.push('');
      lines.push(`**Recommendation:** ${bias.suggestion}`);
      lines.push('');
    }
  }

  // Fact Check
  if (data.factCheck?.verifications?.length) {
    lines.push('## Fact Check');
    lines.push('');
    lines.push(`Overall Score: **${data.factCheck.score}/100**`);
    lines.push('');
    lines.push('| Claim | Verdict | Explanation |');
    lines.push('|-------|---------|-------------|');
    for (const v of data.factCheck.verifications) {
      lines.push(`| ${v.claim.replace(/\|/g, '\\|')} | **${v.verdict}** | ${v.explanation.replace(/\|/g, '\\|')} |`);
    }
    lines.push('');
  }

  // SWOT
  if (data.swotAnalysis) {
    lines.push('## SWOT Analysis');
    lines.push('');
    const sections = [
      { label: 'Strengths', items: data.swotAnalysis.strengths },
      { label: 'Weaknesses', items: data.swotAnalysis.weaknesses },
      { label: 'Opportunities', items: data.swotAnalysis.opportunities },
      { label: 'Threats', items: data.swotAnalysis.threats },
    ];
    for (const section of sections) {
      lines.push(`### ${section.label}`);
      for (const item of section.items) {
        lines.push(`- ${item}`);
      }
      lines.push('');
    }
    if (data.swotAnalysis.strategicAdvice) {
      lines.push(`**Strategic Advice:** ${data.swotAnalysis.strategicAdvice}`);
      lines.push('');
    }
  }

  // Boardroom
  if (data.simulation) {
    lines.push('## Boardroom Simulation');
    lines.push('');
    lines.push(`**Overall Verdict:** ${data.simulation.overallVerdict}`);
    lines.push('');
    if (data.simulation.twins?.length) {
      lines.push('| Persona | Vote | Confidence | Rationale |');
      lines.push('|---------|------|------------|-----------|');
      for (const twin of data.simulation.twins) {
        lines.push(`| ${twin.name} (${twin.role}) | **${twin.vote}** | ${twin.confidence}% | ${twin.rationale.replace(/\|/g, '\\|')} |`);
      }
      lines.push('');
    }
  }

  // Logic
  if (data.logicalAnalysis) {
    lines.push('## Logical Analysis');
    lines.push('');
    lines.push(`Logic Score: **${data.logicalAnalysis.score}/100**`);
    lines.push('');
    if (data.logicalAnalysis.fallacies?.length) {
      for (const f of data.logicalAnalysis.fallacies) {
        lines.push(`- **${f.name}** (\`${f.severity}\`): ${f.explanation}`);
      }
      lines.push('');
    }
  }

  // Noise
  if (data.noiseStats) {
    lines.push('## Noise Analysis');
    lines.push('');
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Mean | ${data.noiseStats.mean.toFixed(2)} |`);
    lines.push(`| Std Dev | ${data.noiseStats.stdDev.toFixed(2)} |`);
    lines.push(`| Variance | ${data.noiseStats.variance.toFixed(2)} |`);
    lines.push('');
  }

  // Compliance
  if (data.compliance) {
    lines.push('## Compliance');
    lines.push('');
    lines.push(`Status: **${data.compliance.status}** | Risk Score: ${data.compliance.riskScore}`);
    lines.push('');
    lines.push(data.compliance.summary);
    lines.push('');
    if (data.compliance.regulations?.length) {
      for (const reg of data.compliance.regulations) {
        lines.push(`- **${reg.name}**: ${reg.status} — ${reg.description}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('*This report was generated by Decision Intel. All analyses are AI-assisted and should be reviewed by qualified professionals.*');

  return lines.join('\n');
}

/**
 * Download a Markdown string as a .md file.
 */
export function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `decision-audit-${filename}.md`;
  a.click();
  URL.revokeObjectURL(url);
}
