/**
 * /api/containers/[id]/premortem-defence — V2 mandatory pre-mortem
 * dissent gate (locked 2026-05-16).
 *
 * POST persists the sponsor's written defence to the Deal-Fever
 * pre-mortem questions onto DecisionContainer.premortemDefence. This is
 * the gate the outcome route enforces (checkPremortemDefenceGate) and
 * the artefact that flows into the DPR human-oversight record. The
 * questions themselves are generated by the existing
 * /api/decisions/[id]/deal-fever-premortem route — this route only
 * records the human's answers. Acquisition-mode only.
 */

import { NextRequest, NextResponse } from 'next/server';
import { Prisma } from '@prisma/client';
import { createClient } from '@/utils/supabase/server';
import { prisma } from '@/lib/prisma';
import { createLogger } from '@/lib/utils/logger';
import { logAudit } from '@/lib/audit';
import {
  MIN_DEFENCE_CHARS,
  type PremortemDefence,
  type PremortemPattern,
} from '@/lib/containers/premortem-defence';

const log = createLogger('PremortemDefenceRoute');

const PATTERNS: ReadonlySet<string> = new Set(['deal_fever', 'winners_curse', 'synergy_mirage']);

interface DefenceBody {
  answers?: Array<{ pattern?: string; question?: string; writtenDefence?: string }>;
}

export async function POST(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params;
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const orgId = await prisma.teamMember
      .findFirst({ where: { userId: user.id }, select: { orgId: true } })
      .then(m => m?.orgId ?? null)
      .catch(() => null);

    const container = await prisma.decisionContainer.findFirst({
      where: { id, OR: [{ orgId: orgId ?? undefined }, { ownerUserId: user.id }] },
      select: { id: true, kind: true },
    });
    if (!container) return NextResponse.json({ error: 'Not found' }, { status: 404 });
    if (container.kind !== 'acquisition') {
      return NextResponse.json(
        { error: 'Pre-mortem defence applies to acquisition-mode decisions only.' },
        { status: 400 }
      );
    }

    const body = (await request.json().catch(() => null)) as DefenceBody | null;
    if (!body || !Array.isArray(body.answers) || body.answers.length === 0) {
      return NextResponse.json(
        { error: 'At least one answered pre-mortem question is required.' },
        { status: 400 }
      );
    }

    const answers: PremortemDefence['answers'] = [];
    for (const a of body.answers) {
      if (!a || typeof a !== 'object') continue;
      if (typeof a.pattern !== 'string' || !PATTERNS.has(a.pattern)) {
        return NextResponse.json({ error: `Invalid pattern: ${a.pattern}` }, { status: 400 });
      }
      if (typeof a.question !== 'string' || a.question.trim().length === 0) {
        return NextResponse.json(
          { error: 'Each answer must carry its verbatim pre-mortem question.' },
          { status: 400 }
        );
      }
      if (
        typeof a.writtenDefence !== 'string' ||
        a.writtenDefence.trim().length < MIN_DEFENCE_CHARS
      ) {
        return NextResponse.json(
          {
            error: `Each written defence must be substantive (≥ ${MIN_DEFENCE_CHARS} characters). Answer the antagonist properly — this goes on the record.`,
          },
          { status: 400 }
        );
      }
      answers.push({
        pattern: a.pattern as PremortemPattern,
        question: a.question.trim(),
        writtenDefence: a.writtenDefence.trim(),
      });
    }
    if (answers.length === 0) {
      return NextResponse.json({ error: 'No valid answers submitted.' }, { status: 400 });
    }

    const defence: PremortemDefence = {
      answers,
      answeredByUserId: user.id,
      answeredAt: new Date().toISOString(),
    };

    // Atomic guarded write — ownership predicate folded into the WHERE
    // (2026-06-06 check-then-act lock) so the write is tenant-scoped, not just
    // the preceding findFirst read.
    const result = await prisma.decisionContainer.updateMany({
      where: { id, OR: [{ orgId: orgId ?? undefined }, { ownerUserId: user.id }] },
      data: { premortemDefence: defence as unknown as Prisma.InputJsonValue },
    });
    if (result.count === 0) {
      return NextResponse.json({ error: 'Not found' }, { status: 404 });
    }

    await logAudit({
      action: 'PREMORTEM_DEFENCE_RECORDED',
      resource: 'decision_container',
      resourceId: id,
      details: { answerCount: answers.length, patterns: answers.map(x => x.pattern) },
    }).catch(err => log.warn('Pre-mortem defence audit log failed:', err));

    return NextResponse.json({ ok: true });
  } catch (error) {
    log.error('POST /api/containers/[id]/premortem-defence failed:', error);
    return NextResponse.json({ error: 'Internal error' }, { status: 500 });
  }
}
