'use client';

import { useState, useEffect, useCallback } from 'react';
import {
  X,
  Download,
  FileText,
  FileJson,
  FileSpreadsheet,
  Copy,
  Check,
  Link2,
  Mail,
  Loader2,
} from 'lucide-react';
import { useToast } from '@/components/ui/ToastContext';

interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  documentName: string;
  analysisData: Record<string, unknown>;
  analysisId?: string;
  onExportPdf: () => Promise<void>;
  onExportCsv: () => void;
  onExportMarkdown: () => void;
  onExportJson: () => void;
}

type ActiveTab = 'export' | 'share';

export function ShareModal({
  isOpen,
  onClose,
  documentName,
  analysisData,
  analysisId,
  onExportPdf,
  onExportCsv,
  onExportMarkdown,
  onExportJson,
}: ShareModalProps) {
  const [activeTab, setActiveTab] = useState<ActiveTab>('export');
  const [exportingPdf, setExportingPdf] = useState(false);
  const [copied, setCopied] = useState(false);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [creatingLink, setCreatingLink] = useState(false);
  const [linkCopied, setLinkCopied] = useState(false);
  const { showToast } = useToast();

  // Escape to close
  useEffect(() => {
    if (!isOpen) return;
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [isOpen, onClose]);

  const handlePdfExport = useCallback(async () => {
    setExportingPdf(true);
    try {
      await onExportPdf();
      showToast('PDF exported', 'success');
    } catch {
      showToast('PDF export failed', 'error');
    } finally {
      setExportingPdf(false);
    }
  }, [onExportPdf, showToast]);

  const handleCopySummary = useCallback(async () => {
    try {
      const summary = (analysisData.summary as string) || 'No summary available';
      const text = `Decision Audit: ${documentName}\nScore: ${Math.round(analysisData.overallScore as number)}/100\n\n${summary}`;
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      showToast('Summary copied to clipboard', 'success');
    } catch {
      showToast('Failed to copy', 'error');
    }
  }, [analysisData, documentName, showToast]);

  const handleCreateShareLink = useCallback(async () => {
    if (!analysisId) return;
    setCreatingLink(true);
    try {
      const res = await fetch('/api/share', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ analysisId, expiresInDays: 7 }),
      });
      if (res.ok) {
        const data = await res.json();
        const url = data.url || `${window.location.origin}/shared/${data.token}`;
        setShareUrl(url);
        await navigator.clipboard.writeText(url);
        setLinkCopied(true);
        setTimeout(() => setLinkCopied(false), 3000);
        showToast('Share link created and copied!', 'success');
      } else {
        const data = await res.json();
        showToast(data.error || 'Failed to create share link', 'error');
      }
    } catch {
      showToast('Failed to create share link', 'error');
    } finally {
      setCreatingLink(false);
    }
  }, [analysisId, showToast]);

  const handleEmailShare = useCallback(() => {
    const subject = encodeURIComponent(`Decision Audit: ${documentName}`);
    const score = Math.round(analysisData.overallScore as number);
    const summary = (analysisData.summary as string) || '';
    const body = encodeURIComponent(
      `Decision Intel Audit Report\n\nDocument: ${documentName}\nDecision Quality Score: ${score}/100\n\n${summary}\n\n---\nGenerated by Decision Intel`
    );
    window.open(`mailto:?subject=${subject}&body=${body}`, '_self');
  }, [analysisData, documentName]);

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: 'rgba(0,0,0,0.7)' }}
      onClick={onClose}
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-label="Share and Export"
        className="card w-full max-w-md"
        style={{
          maxHeight: '85vh',
          overflowY: 'auto',
        }}
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div
          className="card-header flex items-center justify-between"
          style={{ position: 'sticky', top: 0, background: 'var(--bg-secondary)', zIndex: 5 }}
        >
          <div>
            <h3 style={{ fontSize: '15px', fontWeight: 600 }}>Share & Export</h3>
            <p style={{ fontSize: '11px', color: 'var(--text-muted)', margin: 0 }}>
              {documentName}
            </p>
          </div>
          <button
            onClick={onClose}
            style={{
              background: 'transparent',
              border: 'none',
              cursor: 'pointer',
              color: 'var(--text-muted)',
              display: 'flex',
            }}
            aria-label="Close"
          >
            <X size={18} />
          </button>
        </div>

        {/* Tabs */}
        <div
          className="flex"
          style={{
            borderBottom: '1px solid var(--border-color)',
            padding: '0 var(--spacing-lg)',
          }}
        >
          {(['export', 'share'] as const).map(tab => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              style={{
                padding: '10px 16px',
                fontSize: '13px',
                fontWeight: activeTab === tab ? 600 : 400,
                color: activeTab === tab ? 'var(--accent-primary)' : 'var(--text-muted)',
                borderBottom:
                  activeTab === tab ? '2px solid var(--accent-primary)' : '2px solid transparent',
                background: 'transparent',
                border: 'none',
                borderBottomWidth: '2px',
                borderBottomStyle: 'solid',
                cursor: 'pointer',
              }}
            >
              {tab === 'export' ? 'Export' : 'Quick Share'}
            </button>
          ))}
        </div>

        <div style={{ padding: 'var(--spacing-lg)' }}>
          {/* Export Tab */}
          {activeTab === 'export' && (
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px' }}>
              <button
                onClick={handlePdfExport}
                disabled={exportingPdf}
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  gap: '8px',
                  padding: 'var(--spacing-lg)',
                  background: 'var(--bg-primary)',
                  border: '1px solid var(--border-color)',
                  borderRadius: '8px',
                  cursor: 'pointer',
                  color: 'var(--text-primary)',
                  transition: 'border-color 0.15s',
                }}
              >
                {exportingPdf ? (
                  <Loader2 size={24} className="animate-spin" style={{ color: 'var(--error)' }} />
                ) : (
                  <FileText size={24} style={{ color: 'var(--error)' }} />
                )}
                <span style={{ fontSize: '13px', fontWeight: 500 }}>PDF Report</span>
                <span style={{ fontSize: '10px', color: 'var(--text-muted)' }}>
                  Full formatted report
                </span>
              </button>

              <button
                onClick={() => {
                  onExportCsv();
                  showToast('CSV exported', 'success');
                }}
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  gap: '8px',
                  padding: 'var(--spacing-lg)',
                  background: 'var(--bg-primary)',
                  border: '1px solid var(--border-color)',
                  borderRadius: '8px',
                  cursor: 'pointer',
                  color: 'var(--text-primary)',
                  transition: 'border-color 0.15s',
                }}
              >
                <FileSpreadsheet size={24} style={{ color: 'var(--success)' }} />
                <span style={{ fontSize: '13px', fontWeight: 500 }}>CSV Data</span>
                <span style={{ fontSize: '10px', color: 'var(--text-muted)' }}>
                  Spreadsheet format
                </span>
              </button>

              <button
                onClick={() => {
                  onExportMarkdown();
                  showToast('Markdown exported', 'success');
                }}
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  gap: '8px',
                  padding: 'var(--spacing-lg)',
                  background: 'var(--bg-primary)',
                  border: '1px solid var(--border-color)',
                  borderRadius: '8px',
                  cursor: 'pointer',
                  color: 'var(--text-primary)',
                  transition: 'border-color 0.15s',
                }}
              >
                <Download size={24} style={{ color: 'var(--accent-primary)' }} />
                <span style={{ fontSize: '13px', fontWeight: 500 }}>Markdown</span>
                <span style={{ fontSize: '10px', color: 'var(--text-muted)' }}>
                  Documentation format
                </span>
              </button>

              <button
                onClick={() => {
                  onExportJson();
                  showToast('JSON exported', 'success');
                }}
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  gap: '8px',
                  padding: 'var(--spacing-lg)',
                  background: 'var(--bg-primary)',
                  border: '1px solid var(--border-color)',
                  borderRadius: '8px',
                  cursor: 'pointer',
                  color: 'var(--text-primary)',
                  transition: 'border-color 0.15s',
                }}
              >
                <FileJson size={24} style={{ color: 'var(--warning)' }} />
                <span style={{ fontSize: '13px', fontWeight: 500 }}>JSON</span>
                <span style={{ fontSize: '10px', color: 'var(--text-muted)' }}>
                  Structured data
                </span>
              </button>
            </div>
          )}

          {/* Share Tab */}
          {activeTab === 'share' && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              {/* Shareable Link */}
              {analysisId && (
                <div>
                  <button
                    onClick={
                      shareUrl
                        ? async () => {
                            await navigator.clipboard.writeText(shareUrl);
                            setLinkCopied(true);
                            setTimeout(() => setLinkCopied(false), 2000);
                            showToast('Link copied!', 'success');
                          }
                        : handleCreateShareLink
                    }
                    disabled={creatingLink}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '12px',
                      padding: '12px 16px',
                      background: shareUrl ? 'rgba(249, 115, 22, 0.08)' : 'var(--bg-primary)',
                      border: shareUrl
                        ? '1px solid rgba(249, 115, 22, 0.3)'
                        : '1px solid var(--border-color)',
                      borderRadius: '8px',
                      cursor: 'pointer',
                      color: 'var(--text-primary)',
                      fontSize: '13px',
                      textAlign: 'left',
                      width: '100%',
                    }}
                  >
                    {creatingLink ? (
                      <Loader2
                        size={18}
                        className="animate-spin"
                        style={{ color: 'var(--accent-primary)', flexShrink: 0 }}
                      />
                    ) : linkCopied ? (
                      <Check size={18} style={{ color: 'var(--success)', flexShrink: 0 }} />
                    ) : (
                      <Link2 size={18} style={{ color: 'var(--accent-primary)', flexShrink: 0 }} />
                    )}
                    <div>
                      <div style={{ fontWeight: 500 }}>
                        {shareUrl
                          ? linkCopied
                            ? 'Link copied!'
                            : 'Copy share link'
                          : 'Create shareable link'}
                      </div>
                      <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                        {shareUrl
                          ? 'Anyone with this link can view the analysis'
                          : 'Generates a public read-only link (7 day expiry)'}
                      </div>
                    </div>
                  </button>
                  {shareUrl && (
                    <div
                      style={{
                        fontSize: '11px',
                        color: 'var(--text-muted)',
                        padding: '6px 16px',
                        wordBreak: 'break-all',
                        fontFamily: 'monospace',
                      }}
                    >
                      {shareUrl}
                    </div>
                  )}
                </div>
              )}

              <button
                onClick={handleCopySummary}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '12px',
                  padding: '12px 16px',
                  background: 'var(--bg-primary)',
                  border: '1px solid var(--border-color)',
                  borderRadius: '8px',
                  cursor: 'pointer',
                  color: 'var(--text-primary)',
                  fontSize: '13px',
                  textAlign: 'left',
                }}
              >
                {copied ? (
                  <Check size={18} style={{ color: 'var(--success)', flexShrink: 0 }} />
                ) : (
                  <Copy size={18} style={{ color: 'var(--accent-primary)', flexShrink: 0 }} />
                )}
                <div>
                  <div style={{ fontWeight: 500 }}>Copy summary to clipboard</div>
                  <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                    Score + executive summary as plain text
                  </div>
                </div>
              </button>

              <button
                onClick={() => {
                  onExportMarkdown();
                  showToast('Copied Markdown to clipboard', 'success');
                }}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '12px',
                  padding: '12px 16px',
                  background: 'var(--bg-primary)',
                  border: '1px solid var(--border-color)',
                  borderRadius: '8px',
                  cursor: 'pointer',
                  color: 'var(--text-primary)',
                  fontSize: '13px',
                  textAlign: 'left',
                }}
              >
                <Link2 size={18} style={{ color: 'var(--accent-primary)', flexShrink: 0 }} />
                <div>
                  <div style={{ fontWeight: 500 }}>Export as Markdown</div>
                  <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                    Full report in Markdown format
                  </div>
                </div>
              </button>

              <button
                onClick={handleEmailShare}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '12px',
                  padding: '12px 16px',
                  background: 'var(--bg-primary)',
                  border: '1px solid var(--border-color)',
                  borderRadius: '8px',
                  cursor: 'pointer',
                  color: 'var(--text-primary)',
                  fontSize: '13px',
                  textAlign: 'left',
                }}
              >
                <Mail size={18} style={{ color: 'var(--accent-primary)', flexShrink: 0 }} />
                <div>
                  <div style={{ fontWeight: 500 }}>Send via email</div>
                  <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                    Opens your email client with summary
                  </div>
                </div>
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
